<a href="https://colab.research.google.com/github/Patsee/data_viz/blob/main/More_advanced_data_structure.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Dictionary
สามารถ index ด้วยอะไรก็ได้ แต่ลำดับจะหายไป

In [ ]:
ex_dict = {'a' : 1 ,'1' :1, 'stat' :5} #curly bracket ในการบอกว่าเป็น dict

In [ ]:
ex_dict['stat']

5

In [ ]:
ex2_dict = {1:'one', 2:'two', 3 : 'three' }

In [ ]:
ex2_dict[2]

'two'

#### การเพิ่มสมาชิก

In [ ]:
ex2_dict[0] = 'zero'

In [ ]:
ex2_dict

{0: 'zero', 1: 'one', 2: 'two', 3: 'three'}

คำสั่ง

In [ ]:
ex2_dict.keys()

dict_keys([1, 2, 3, 0])

In [ ]:
for  index in ex2_dict.keys() :
   print(index)

1
2
3
0


In [ ]:
ex2_dict.values()

dict_values(['one', 'two', 'three', 'zero'])

In [ ]:
index

0

numpy

numpy คือ package ที่ทำงานเกี่ยวกับ array ของตัวเลข(ที่มีคนเขียนขึ้นมาและนิยมใช้) \
numpy -> number python

In [ ]:
import numpy #วิธีเรียกใช้งาน package

In [ ]:
ex_2d_array = numpy.array([[5.2,3.0,4.5],[9.1,0.1,0.3]])
print(ex_2d_array)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]


In [ ]:
ex_2d_array[1,2]

0.3

In [ ]:
list_x = [[5.2,3.0,4.5],[9.1,0.1,0.3]] #การชี้ list
print(len(list_x))
print(list_x[1])
print(list_x[1][2])

2
[9.1, 0.1, 0.3]
0.3


### operatios

In [ ]:
ex2_2d_array = numpy.array([[1,0,0],[0,0,1]])
print(ex2_2d_array)
print(ex_2d_array)

[[1 0 0]
 [0 0 1]]
[[5.2 3.  4.5]
 [9.1 0.1 0.3]]


In [ ]:
ex_2d_array.shape #ตรวจสอบขนาดของ matrix

(2, 3)

In [ ]:
ex_2d_array + ex2_2d_array

array([[6.2, 3. , 4.5],
       [9.1, 0.1, 1.3]])

In [ ]:
list_x = [[5.2,3.0,4.5],[9.1,0.1,0.3]] 
list_x2 = [[1,0,1],[0,1,1]] 
list_x + list_x2

[[5.2, 3.0, 4.5], [9.1, 0.1, 0.3], [1, 0, 1], [0, 1, 1]]

In [ ]:
ex_2d_array * ex2_2d_array

array([[5.2, 0. , 0. ],
       [0. , 0. , 0.3]])

In [ ]:
print(ex_2d_array)
print(ex_2d_array.T)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]
[[5.2 9.1]
 [3.  0.1]
 [4.5 0.3]]


In [ ]:
dot_mat = numpy.dot(ex_2d_array.T,ex2_2d_array)
print(dot_mat)

[[5.2 0.  9.1]
 [3.  0.  0.1]
 [4.5 0.  0.3]]


search google -> web stackoverflow

In [ ]:
numpy.linalg.det(dot_mat)


0.0

## matrix slicing

In [ ]:
print(ex_2d_array)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]


In [ ]:
ex_2d_array[1,1:]

array([0.1, 0.3])

In [ ]:
ex_2d_array[:,:2]

array([[5.2, 3. ],
       [9.1, 0.1]])

### HW 5


เขียน function คูณ matrix \
แล้ว test กับ matrix \
(2,3)*(3,2)  \
(4,4)*(4,1)  \
(2,2)*(2,2)  \

In [ ]:
import numpy as nup

In [ ]:
M_1 = nup.array([[3,5,6],[5,6,2]])
M_1 #matrix 2*3

array([[3, 5, 6],
       [5, 6, 2]])

In [ ]:
M_2 = nup.array([[23,12],[61,18],[12,9]])
M_2  #matrix 3*2

array([[23, 12],
       [61, 18],
       [12,  9]])

In [ ]:
M_3 = nup.array([[4,10,12,5],[6,3,4,9,],[15,20,32,11],[10,21,8,7]])
M_3 #matrix 4*4

array([[ 4, 10, 12,  5],
       [ 6,  3,  4,  9],
       [15, 20, 32, 11],
       [10, 21,  8,  7]])

In [ ]:
M_4 = nup.array([[23],[23],[12],[17]])
M_4 #matrix 4*1

array([[23],
       [23],
       [12],
       [17]])

In [ ]:
M_5 = nup.array([[3,7],[8,3]])
M_5 #matrix 2*2

array([[3, 7],
       [8, 3]])

In [ ]:
M_6= nup.array([[11,4],[5,5]])
M_6 #matrix 2*2

array([[11,  4],
       [ 5,  5]])

In [ ]:
def mul_matrix(X, Y):
    M = [[0 for row in range(len(Y[0]))] for col in range(len(X))]
    for i in range(len(X)):
        for j in range(len(Y[0])):
            for k in range(len(Y)):
                M[i][j] += X[i][k]* Y[k][j]
    m = nup.matrix(M)
    return m      

In [ ]:
mul_matrix(M_1,M_2)

matrix([[446, 180],
        [505, 186]])

In [ ]:
mul_matrix(M_3,M_4)

matrix([[ 551],
        [ 408],
        [1376],
        [ 928]])

In [ ]:
mul_matrix(M_5,M_6)

matrix([[ 68,  47],
        [103,  47]])

## zeros,ones,randon

In [2]:
import numpy as np #import numpy แล้วตั้งชื่อ np

In [3]:
np.zeros(2)


array([0., 0.])

In [4]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

## ones

In [5]:
np.ones(2)

array([1., 1.])

In [7]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

# Metrix Operation (scalar multiplication)

In [8]:
M_one = np.ones((2,3))

In [9]:
2*M_one

array([[2., 2., 2.],
       [2., 2., 2.]])

## random numpy

In [11]:
import numpy as np

In [22]:
np.random.rand(3,2) #uniforn random [0,1)

array([[0.70180615, 0.8793031 ],
       [0.9545839 , 0.04417176],
       [0.64739099, 0.39903737]])

In [17]:
np.random.rand(3,2,3)

array([[[0.78689097, 0.4344601 , 0.50485377],
        [0.03477925, 0.78531803, 0.98571263]],

       [[0.88512995, 0.36485883, 0.20198271],
        [0.19274327, 0.25421964, 0.87477429]],

       [[0.04995257, 0.19884299, 0.06575976],
        [0.36064537, 0.95500549, 0.44565841]]])

In [23]:
np.random.randn(3,2) #random normal mean=0 var=1

array([[ 0.36350269, -1.87653118],
       [-0.15016655, -0.60711154],
       [-1.44289512, -0.21968979]])

In [26]:
 np.random.choice(5, 3)

array([0, 0, 4])

In [28]:
 np.random.choice([1,2,3,'a','b'])

'b'

In [36]:
 np.random.choice([1,2,3,4,5,6,7,8,9,0], size = (2,3) , replace=False)

array([[8, 1, 2],
       [3, 4, 7]])

In [41]:
 np.random.choice(['A' , 'B' , 'C' , 'D' , 'F'], size=35, p = [0.1,0.2,0.4 ,0.29,0.01] )

array(['A', 'B', 'C', 'D', 'D', 'C', 'C', 'D', 'C', 'C', 'C', 'C', 'A',
       'C', 'D', 'C', 'C', 'C', 'A', 'C', 'B', 'C', 'D', 'C', 'C', 'D',
       'C', 'C', 'C', 'B', 'C', 'D', 'B', 'D', 'C'], dtype='<U1')

## เฉลย HW Matrix Multiplication

In [61]:
def mat_mul(A,B) :
  C = np.zeros((A.shape[0],B.shape[1]))#เตรียมขนาดของ matrix ผลลัพธ์
  for r_a in range(A.shape[0]) :
    for c_b in range(B.shape[1]) :
      for every_element in range(A.shape[1]) :
        C[r_a,c_b] = C[r_a,c_b] + (A[r_a,every_element] * B[every_element,c_b])
  return C

In [59]:
mat1= np.array([[1,2,3],[4,5,6]])
mat2= np.array([[7,8],[9,10],[11,12]])

In [62]:
mat_mul(mat1,mat2)

array([[ 58.,  64.],
       [139., 154.]])