<a href="https://colab.research.google.com/github/Patsee/data_viz/blob/main/More_advanced_data_structure.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Dictionary
สามารถ index ด้วยอะไรก็ได้ แต่ลำดับจะหายไป

In [ ]:
ex_dict = {'a' : 1 ,'1' :1, 'stat' :5} #curly bracket ในการบอกว่าเป็น dict

In [ ]:
ex_dict['stat']

5

In [ ]:
ex2_dict = {1:'one', 2:'two', 3 : 'three' }

In [ ]:
ex2_dict[2]

'two'

#### การเพิ่มสมาชิก

In [ ]:
ex2_dict[0] = 'zero'

In [ ]:
ex2_dict

{0: 'zero', 1: 'one', 2: 'two', 3: 'three'}

คำสั่ง

In [ ]:
ex2_dict.keys()

dict_keys([1, 2, 3, 0])

In [ ]:
for  index in ex2_dict.keys() :
   print(index)

1
2
3
0


In [ ]:
ex2_dict.values()

dict_values(['one', 'two', 'three', 'zero'])

In [ ]:
index

0

numpy

numpy คือ package ที่ทำงานเกี่ยวกับ array ของตัวเลข(ที่มีคนเขียนขึ้นมาและนิยมใช้) \
numpy -> number python

In [ ]:
import numpy #วิธีเรียกใช้งาน package

In [ ]:
ex_2d_array = numpy.array([[5.2,3.0,4.5],[9.1,0.1,0.3]])
print(ex_2d_array)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]


In [ ]:
ex_2d_array[1,2]

0.3

In [ ]:
list_x = [[5.2,3.0,4.5],[9.1,0.1,0.3]] #การชี้ list
print(len(list_x))
print(list_x[1])
print(list_x[1][2])

2
[9.1, 0.1, 0.3]
0.3


### operatios

In [ ]:
ex2_2d_array = numpy.array([[1,0,0],[0,0,1]])
print(ex2_2d_array)
print(ex_2d_array)

[[1 0 0]
 [0 0 1]]
[[5.2 3.  4.5]
 [9.1 0.1 0.3]]


In [ ]:
ex_2d_array.shape #ตรวจสอบขนาดของ matrix

(2, 3)

In [ ]:
ex_2d_array + ex2_2d_array

array([[6.2, 3. , 4.5],
       [9.1, 0.1, 1.3]])

In [ ]:
list_x = [[5.2,3.0,4.5],[9.1,0.1,0.3]] 
list_x2 = [[1,0,1],[0,1,1]] 
list_x + list_x2

[[5.2, 3.0, 4.5], [9.1, 0.1, 0.3], [1, 0, 1], [0, 1, 1]]

In [ ]:
ex_2d_array * ex2_2d_array

array([[5.2, 0. , 0. ],
       [0. , 0. , 0.3]])

In [ ]:
print(ex_2d_array)
print(ex_2d_array.T)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]
[[5.2 9.1]
 [3.  0.1]
 [4.5 0.3]]


In [ ]:
dot_mat = numpy.dot(ex_2d_array.T,ex2_2d_array)
print(dot_mat)

[[5.2 0.  9.1]
 [3.  0.  0.1]
 [4.5 0.  0.3]]


search google -> web stackoverflow

In [ ]:
numpy.linalg.det(dot_mat)


0.0

## matrix slicing

In [ ]:
print(ex_2d_array)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]


In [ ]:
ex_2d_array[1,1:]

array([0.1, 0.3])

In [ ]:
ex_2d_array[:,:2]

array([[5.2, 3. ],
       [9.1, 0.1]])

### HW 5


เขียน function คูณ matrix \
แล้ว test กับ matrix \
(2,3)*(3,2)  \
(4,4)*(4,1)  \
(2,2)*(2,2)  \

In [63]:
import numpy as nup

In [64]:
M_1 = nup.array([[3,5,6],[5,6,2]])
M_1 #matrix 2*3

array([[3, 5, 6],
       [5, 6, 2]])

In [65]:
M_2 = nup.array([[23,12],[61,18],[12,9]])
M_2  #matrix 3*2

array([[23, 12],
       [61, 18],
       [12,  9]])

In [66]:
M_3 = nup.array([[4,10,12,5],[6,3,4,9,],[15,20,32,11],[10,21,8,7]])
M_3 #matrix 4*4

array([[ 4, 10, 12,  5],
       [ 6,  3,  4,  9],
       [15, 20, 32, 11],
       [10, 21,  8,  7]])

In [67]:
M_4 = nup.array([[23],[23],[12],[17]])
M_4 #matrix 4*1

array([[23],
       [23],
       [12],
       [17]])

In [68]:
M_5 = nup.array([[3,7],[8,3]])
M_5 #matrix 2*2

array([[3, 7],
       [8, 3]])

In [69]:
M_6= nup.array([[11,4],[5,5]])
M_6 #matrix 2*2

array([[11,  4],
       [ 5,  5]])

In [70]:
def mul_matrix(X, Y):
    M = [[0 for row in range(len(Y[0]))] for col in range(len(X))]
    for i in range(len(X)):
        for j in range(len(Y[0])):
            for k in range(len(Y)):
                M[i][j] += X[i][k]* Y[k][j]
    m = nup.matrix(M)
    return m      

In [71]:
mul_matrix(M_1,M_2)

matrix([[446, 180],
        [505, 186]])

In [72]:
mul_matrix(M_3,M_4)

matrix([[ 551],
        [ 408],
        [1376],
        [ 928]])

In [73]:
mul_matrix(M_5,M_6)

matrix([[ 68,  47],
        [103,  47]])